// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCor96COcHpUkiuqLhp3dllgJQiuPSwovk',
    appId: '1:676250189840:web:c93fb3b74d7f16ac8aca95',
    messagingSenderId: '676250189840',
    projectId: 'safetyapp-ac4a5',
    authDomain: 'safetyapp-ac4a5.firebaseapp.com',
    storageBucket: 'safetyapp-ac4a5.appspot.com',
    measurementId: 'G-BQLF021VSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx1BuLg7QQR7QS0fBYTkuolvZgtxPPrew',
    appId: '1:676250189840:android:7ad7811df36bed5b8aca95',
    messagingSenderId: '676250189840',
    projectId: 'safetyapp-ac4a5',
    storageBucket: 'safetyapp-ac4a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA--WDEwg7R5QJAhFJmmuh13pZyto6NDe0',
    appId: '1:676250189840:ios:358087ae5696fb108aca95',
    messagingSenderId: '676250189840',
    projectId: 'safetyapp-ac4a5',
    storageBucket: 'safetyapp-ac4a5.appspot.com',
    iosBundleId: 'com.example.safeti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA--WDEwg7R5QJAhFJmmuh13pZyto6NDe0',
    appId: '1:676250189840:ios:7b52a899eba06d358aca95',
    messagingSenderId: '676250189840',
    projectId: 'safetyapp-ac4a5',
    storageBucket: 'safetyapp-ac4a5.appspot.com',
    iosBundleId: 'com.example.safeti.RunnerTests',
  );
}
